# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: blobcache.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    AsyncIterable,
    AsyncIterator,
    Dict,
    Iterable,
    Optional,
    Union,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class GetContentRequest(betterproto.Message):
    hash: str = betterproto.string_field(1)
    offset: int = betterproto.int64_field(2)
    length: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class GetContentResponse(betterproto.Message):
    content: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class StoreContentRequest(betterproto.Message):
    content: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class StoreContentResponse(betterproto.Message):
    hash: str = betterproto.string_field(1)


class BlobCacheStub(betterproto.ServiceStub):
    async def get_content(
        self,
        get_content_request: "GetContentRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetContentResponse":
        return await self._unary_unary(
            "/blobcache.BlobCache/GetContent",
            get_content_request,
            GetContentResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def store_content(
        self,
        store_content_request_iterator: Union[
            AsyncIterable["StoreContentRequest"], Iterable["StoreContentRequest"]
        ],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "StoreContentResponse":
        return await self._stream_unary(
            "/blobcache.BlobCache/StoreContent",
            store_content_request_iterator,
            StoreContentRequest,
            StoreContentResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BlobCacheBase(ServiceBase):

    async def get_content(
        self, get_content_request: "GetContentRequest"
    ) -> "GetContentResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def store_content(
        self, store_content_request_iterator: AsyncIterator["StoreContentRequest"]
    ) -> "StoreContentResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_content(
        self, stream: "grpclib.server.Stream[GetContentRequest, GetContentResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_content(request)
        await stream.send_message(response)

    async def __rpc_store_content(
        self, stream: "grpclib.server.Stream[StoreContentRequest, StoreContentResponse]"
    ) -> None:
        request = stream.__aiter__()
        response = await self.store_content(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/blobcache.BlobCache/GetContent": grpclib.const.Handler(
                self.__rpc_get_content,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetContentRequest,
                GetContentResponse,
            ),
            "/blobcache.BlobCache/StoreContent": grpclib.const.Handler(
                self.__rpc_store_content,
                grpclib.const.Cardinality.STREAM_UNARY,
                StoreContentRequest,
                StoreContentResponse,
            ),
        }
